url: https://natashapetrus.com
compression: true
assets:
  sources:
    - _assets/css
    - _assets/js
    - _assets/img
    - _assets/img/bg
    - _assets/img/icon
    - _assets/fonts
    - _assets/fonts/font-awesome
    - _assets/fonts/josefin-sans
  features:
    automatic_img_alt: true
    automatic_img_size: false
  compress:
    css:  sass
    js:   uglifier
exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - .DS_Store
  - notes.txt
include:
  - CNAME
  - robots.txt
  - sitemap.xml
  - browserconfig.xml
  - favicon.ico
  - manifest.json